# Generated by Django 3.2.6 on 2021-08-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fila',
            old_name='idfuncionario',
            new_name='funcionario',
        ),
    ]
